### PR TITLE
feat: add GitHub workflows to check format, lint and test

### PR DESCRIPTION
**Pull request by patheard**
# Summary
Add the following:
- GitHub workflows to test PR code and Docker image build
- Basic unit tests using Vitest.  This includes splitting the original `index.js` into an `app.js` and `server.js` so that the server doesn't automatically start during unit test runs.

# Related
- https://github.com/cds-snc/platform-forms-client/issues/4128

### CODE REVIEW

**Comment by wmoussa-gc** [comment]
I was hoping we could leverage vitest instead of jest as a more modern test framework.

**Comment by patheard** [comment]
> I was hoping we could leverage vitest instead of jest as a more modern test framework.

I have no objections to using vitest - I just went with jest out of habit.  Let me see what's required to switch things over

**Comment by craigzour** [comment]
We should also look into Typescript integration as soon as possible to avoid starting to write stuff in Javascript that we will need to be converted later on. I can probably take this on next week. cc @patheard @wmoussa-gc

**Comment by craigzour** [comment]
> I was hoping we could leverage vitest instead of jest as a more modern test framework.

On that note, while investigating on the memory leak stuff, I noticed that some big libraries we use in the GC Forms web app are using https://pnpm.io/ as package manager. Could be worth taking a look as well!

**Comment by patheard** [comment]
So that was shockingly easy to switch to vitest and it removed all the babel pieces to get jest to support es6 import/export syntax.

Also totally agree about Typescript and looking at another package manager - we're at the perfect time to do it!

**Review by wmoussa-gc — APPROVED** [review]
lgtm!

**Pull request merged**
